

export const USER_LOGIN_REQ = "USER_LOGIN_REQ"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"
export const USER_LOGOUT = "USER_LOGOUT"


export const USER_REGISTER_REQ = "USER_REGISTER_REQ"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE"


export const USER_UPDATE_REQ = "USER_UPDATE_REQ"
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE"


export const GET_AUTH_USER_REQ = 'GET_AUTH_USER_REQ'
export const GET_AUTH_USER_REQ_SUCCESS = 'GET_AUTH_USER_REQ_SUCCESS'
export const GET_AUTH_USER_REQ_FAIL = 'GET_AUTH_USER_REQ_FAIL'


export const GET_ALL_TOPICS = "GET_ALL_TOPICS";
export const GET_SINGLE_TOPIC = "GET_SINGLE_TOPIC";
export const SET_ACTIVE_TOPIC = "SET_ACTIVE_TOPIC";
export const TOPIC_REQ_SUCCESS = "TOPIC_REQ_SUCCESS";
export const TOPIC_REQ_ERROR = "TOPIC_REQ_ERROR";
export const SET_TOPIC_CATEGORY = "SET_TOPIC_CATEGORY";
export const RESET_TOPIC_CATEGORY = "RESET_TOPIC_CATEGORY";


export const GET_TIMELINE_REQ = "GET_TIMELINE_REQ"
export const GET_TIMELINE_SUCCESS = "GET_TIMELINE_SUCCESS"
export const GET_TIMELINE_FAILURE = "GET_TIMELINE_FAILURE"
export const LIKE_TIMELINE_POST = "LIKE_TIMELINE_POST"
export const UNLIKE_TIMELINE_POST = "UNLIKE_TIMELINE_POST"
export const DISLIKE_TIMELINE_POST = "DISLIKE_TIMELINE_POST"
export const UNDISLIKE_TIMELINE_POST = "UNDISLIKE_TIMELINE_POST"
export const COMMENT_TIMELINE_POST = "COMMENT_TIMELINE_POST"
export const DELETE_COMMENT_TIMELINE_POST = "DELETE_COMMENT_TIMELINE_POST"
export const DELETE_TIMELINE_POST = "DELETE_TIMELINE_POST"


export const GET_POST_BY_ID = "GET_POST_BY_ID"
export const LIKE_POST = "LIKE_POST"
export const UNLIKE_POST = "UNLIKE_POST"
export const SEND_COMMENT_POST = "SEND_COMMENT_POST"
export const DELETE_COMMENT_POST = "DELETE_COMMENT_POST"
export const POST_ACTIONS_LOADING = "POST_ACTIONS_LOADING"
export const POST_ACTIONS_FAILURE = "POST_ACTIONS_FAILURE"


export const SEND_NEW_POST_SUCCESS = "SEND_NEW_POST_SUCCESS"
export const SEND_NEW_POST_IMAGE = "SEND_NEW_POST_IMAGE"
export const CLEAR_NEW_POST_IMAGE = "CLEAR_NEW_POST_IMAGE"
export const SEND_NEW_POST_LOADING = "SEND_NEW_POST_LOADING"
export const SEND_NEW_POST_FAILURE = "SEND_NEW_POST_FAILURE"
export const RESET_NEW_POST = "RESET_NEW_POST"
export const RESET_NEW_POST_ERROR = "RESET_NEW_POST_ERROR"
